from __future__ import annotations

import random
from collections import deque
from typing import Deque, Dict, Iterable, List

MALE_NAMES: List[str] = [
    "Aaron",
    "Adam",
    "Adrian",
    "Alan",
    "Albert",
    "Alex",
    "Alfred",
    "Andrew",
    "Anthony",
    "Arnold",
    "Arthur",
    "Austin",
    "Benjamin",
    "Blake",
    "Brandon",
    "Brian",
    "Bruce",
    "Bryan",
    "Caleb",
    "Cameron",
    "Carl",
    "Carlos",
    "Carter",
    "Charles",
    "Chris",
    "Christian",
    "Christopher",
    "Clayton",
    "Cody",
    "Colin",
    "Connor",
    "Craig",
    "Damian",
    "Daniel",
    "Darren",
    "David",
    "Dean",
    "Dennis",
    "Derek",
    "Dominic",
    "Donald",
    "Douglas",
    "Dylan",
    "Edward",
    "Elijah",
    "Eric",
    "Ethan",
    "Evan",
    "Felix",
    "Francis",
    "Frank",
    "Gabriel",
    "Gareth",
    "Gavin",
    "George",
    "Gerald",
    "Grant",
    "Gregory",
    "Harold",
    "Harry",
    "Henry",
    "Howard",
    "Hugh",
    "Hunter",
    "Ian",
    "Isaac",
    "Jack",
    "Jacob",
    "Jake",
    "James",
    "Jason",
    "Jeffrey",
    "Jeremy",
    "Jesse",
    "Jim",
    "Joel",
    "John",
    "Jonah",
    "Jonathan",
    "Jordan",
    "Joseph",
    "Joshua",
    "Justin",
    "Keith",
    "Kenneth",
    "Kevin",
    "Kyle",
    "Lance",
    "Larry",
    "Lawrence",
    "Leo",
    "Leonard",
    "Liam",
    "Logan",
    "Louis",
    "Lucas",
    "Marcus",
    "Mark",
    "Martin",
    "Mason",
    "Matthew",
    "Michael",
    "Mitchell",
    "Nathan",
    "Nicholas",
    "Noah",
    "Oliver",
    "Oscar",
    "Patrick",
    "Paul",
    "Peter",
    "Philip",
    "Raymond",
    "Richard",
    "Robert",
    "Roger",
    "Ryan",
    "Samuel",
    "Scott",
    "Sean",
    "Simon",
    "Spencer",
    "Stephen",
    "Steven",
    "Thomas",
    "Timothy",
    "Victor",
    "Vincent",
    "Walter",
    "Wayne",
    "Wesley",
    "William",
    "Zachary",
]

FEMALE_NAMES: List[str] = [
    "Abigail",
    "Ada",
    "Addison",
    "Alexandra",
    "Alicia",
    "Allison",
    "Alyssa",
    "Amanda",
    "Amber",
    "Amelia",
    "Amy",
    "Andrea",
    "Angela",
    "Anna",
    "Anne",
    "Annie",
    "April",
    "Ariana",
    "Ashley",
    "Audrey",
    "Autumn",
    "Ava",
    "Barbara",
    "Bella",
    "Bethany",
    "Beverly",
    "Bianca",
    "Brenda",
    "Brianna",
    "Brooke",
    "Candice",
    "Carla",
    "Carmen",
    "Caroline",
    "Cassandra",
    "Catherine",
    "Charlotte",
    "Chloe",
    "Christina",
    "Christine",
    "Claire",
    "Clara",
    "Courtney",
    "Daisy",
    "Dana",
    "Danielle",
    "Deborah",
    "Denise",
    "Destiny",
    "Diana",
    "Donna",
    "Dorothy",
    "Eden",
    "Edith",
    "Eleanor",
    "Elena",
    "Elisa",
    "Elizabeth",
    "Ella",
    "Ellen",
    "Emily",
    "Emma",
    "Erica",
    "Erin",
    "Esme",
    "Esther",
    "Eva",
    "Evelyn",
    "Faith",
    "Felicia",
    "Fiona",
    "Flora",
    "Frances",
    "Gabriella",
    "Gail",
    "Gemma",
    "Georgia",
    "Grace",
    "Haley",
    "Hannah",
    "Heather",
    "Heidi",
    "Helen",
    "Holly",
    "Isabella",
    "Jackie",
    "Jade",
    "Jamie",
    "Jane",
    "Jasmine",
    "Jenna",
    "Jennifer",
    "Jessica",
    "Jill",
    "Joanna",
    "Jocelyn",
    "Jordan",
    "Josephine",
    "Joy",
    "Judith",
    "Julia",
    "Julie",
    "June",
    "Kaitlyn",
    "Karen",
    "Katherine",
    "Kathleen",
    "Kayla",
    "Kelly",
    "Kelsey",
    "Kimberly",
    "Kristin",
    "Kylie",
    "Laura",
    "Lauren",
    "Leah",
    "Lillian",
    "Lily",
    "Linda",
    "Lindsay",
    "Lisa",
    "Lola",
    "Lucia",
    "Lucy",
    "Lydia",
    "Madison",
    "Maggie",
    "Margaret",
    "Maria",
    "Mariah",
    "Martha",
    "Megan",
    "Melanie",
    "Melissa",
    "Mia",
    "Michelle",
    "Molly",
    "Monica",
    "Nadia",
    "Naomi",
    "Natalie",
    "Nicole",
    "Nina",
    "Olivia",
    "Paige",
    "Patricia",
    "Paula",
    "Pearl",
    "Penelope",
    "Phoebe",
    "Rachel",
    "Rebecca",
    "Riley",
    "Rose",
    "Sabrina",
    "Samantha",
    "Sandra",
    "Sara",
    "Sarah",
    "Savannah",
    "Scarlett",
    "Sophia",
    "Sophie",
    "Stacy",
    "Stephanie",
    "Susan",
    "Sydney",
    "Taylor",
    "Teresa",
    "Tiffany",
    "Vanessa",
    "Veronica",
    "Victoria",
    "Violet",
    "Vivian",
    "Wendy",
    "Whitney",
    "Zoe",
]

# 扩充常见英文名（包含大量中性名），用于统一的 500 个名字池
ADDITIONAL_NAMES: List[str] = [
    # A
    "Abby", "Abel", "Abraham", "Ace", "Ada", "Adaline", "Addie", "Adeline", "Adley", "Adrianne",
    "Afton", "Agnes", "Aidan", "Aileen", "Aimee", "Ainsley", "Alaina", "Alana", "Alani", "Alanna",
    "Alannah", "Alayna", "Alba", "Albertina", "Aldo", "Aleah", "Alejandra", "Alejandro", "Alexandria",
    "Alexia", "Alia", "Alina", "Alisa", "Alisha", "Alivia", "Aliyah", "Aliza", "Allie", "Alma",
    "Alondra", "Althea", "Alton", "Alyson", "Amani", "Amari", "Amaris", "Amaya", "Amberly", "Amelie",
    "America", "Amira", "Amiya", "Amiyah", "Anais", "Anaya", "Anderson", "Andre", "Andres", "Andy",
    "Angelina", "Angie", "Anika", "Annabel", "Annabella", "Annabelle", "Annalise", "Antoine", "Antonia",
    "Arden", "Arely", "Ari", "Ariadne", "Arianna", "Ariel", "Arlo", "Armani", "Artemis", "Arya",
    "Ash", "Ashlyn", "Ashtyn", "Aspen", "Astrid", "Athena", "Aubree", "Aubri", "Aubrianna", "Audrina",
    "August", "Aura", "Aurora", "Austen", "Avalyn", "Aviana", "Avi", "Axel",
    # B
    "Bailee", "Basil", "Baylee", "Beau", "Beck", "Beckett", "Belle", "Ben", "Benedict", "Bennett",
    "Benson", "Bentley", "Berenice", "Bernard", "Bernice", "Bert", "Berta", "Bessie", "Betsy", "Betty",
    "Billie", "Blaine", "Blaire", "Blaise", "Blanca", "Blessing", "Bodhi", "Boyd", "Braxton", "Brayden",
    "Breanna", "Brenna", "Brenton", "Brianne", "Bria", "Bridget", "Bridger", "Briella", "Brielle",
    "Brinley", "Bristol", "Britt", "Brook", "Brooklyn", "Brooks", "Bryant", "Bryn", "Brynlee",
    # C
    "Cadence", "Caiden", "Caitlin", "Caitlyn", "Cale", "Calla", "Callum", "Camden", "Camille", "Campbell",
    "Candace", "Carlee", "Carlie", "Carlton", "Carly", "Carolina", "Carolyn", "Case", "Casey", "Cathleen",
    "Cayden", "Cecelia", "Celeste", "Celia", "Chance", "Chandler", "Channing", "Chantal", "Charity",
    "Charlene", "Chrissy", "Christa", "Christiana", "Christie", "Ciara", "Clare", "Clarence", "Clarissa",
    "Clement", "Clifton", "Clyde", "Coby", "Colette", "Collin", "Colt", "Colton", "Constance", "Cora",
    "Corbin", "Corinne", "Crysta", "Crystal", "Curtis",
    # D
    "Daelyn", "Dalton", "Damien", "Dane", "Danica", "Daniella", "Darcy", "Daria", "Darla", "Darnell",
    "Darrell", "Darwin", "Deacon", "Deena", "Deja", "Delaney", "Delia", "Delilah", "Delphine", "Demetri",
    "Derrick", "Desiree", "Dexter", "Diamond", "Dillon", "Dominique", "Dorian", "Dorothy", "Dulce",
    "Dwayne", "Dwight",
    # E
    "Easton", "Elektra", "Eliana", "Elias", "Elin", "Elina", "Elisabeth", "Eliza", "Elle", "Elodie",
    "Eloise", "Elora", "Elsa", "Elsie", "Elton", "Ember", "Emersyn", "Emilia", "Emmaline", "Enzo",
    "Ephraim", "Esperanza", "Esteban", "Estella", "Estelle", "Everett", "Evie", "Ezekiel", "Ezra",
    # F
    "Farrah", "Felipe", "Fern", "Finley", "Fisher", "Flynn", "Forrest", "Francesca", "Frida", "Fritz",
    # G
    "Gannon", "Garrison", "Gemma", "Genesis", "Genevieve", "Gideon", "Gilbert", "Glenn", "Godfrey",
    "Graham", "Grayson", "Grey", "Guillermo", "Gunner", "Gus", "Gwendolyn",
    # H
    "Hallie", "Hanna", "Harlow", "Harris", "Harvey", "Haven", "Hayley", "Heath", "Helena", "Hershel",
    "Horace", "Houston", "Hugo",
    # I
    "Igor", "Imani", "Ina", "Ines", "Irma", "Isa", "Isabela", "Isabelle", "Isaias", "Ismael", "Iyla",
    # J
    "Jace", "Jair", "Jayce", "Jayla", "Jaylen", "Jazmine", "Jeanette", "Jefferson", "Jemima", "Jett",
    "Jodie", "Jody", "Johanna", "Jolene", "Joni", "Juliette",
    # K
    "Kaia", "Kali", "Karis", "Karina", "Karla", "Karlee", "Karley", "Karly", "Karson", "Karter",
    "Kassandra", "Katelin", "Katrina", "Kay", "Keaton", "Kennedy", "Kiana", "Kiara", "Kiera", "Kieran",
    "Kim", "Kimber", "Kingsley", "Kinsley", "Kira", "Kori", "Kristine", "Kyla",
    # L
    "Laila", "Lane", "Langston", "Lara", "Layla", "Lea", "Leann", "Leanna", "Leanne", "Leighton",
    "Leila", "Leilani", "Lena", "Leonel", "Lesley", "Libby", "Lila", "Lilian", "Lilliana", "Lillie",
    "Livia", "Liz", "Lizbeth", "London", "Lori", "Lorraine", "Lou", "Louisa", "Louise", "Luca",
    "Luciana", "Lynn",
    # M
    "Macey", "Mack", "Madalyn", "Madalynn", "Mae", "Maeve", "Magnus", "Maia", "Maisie", "Makayla",
    "Malachi", "Marc", "Marcel", "Marcella", "Marci", "Marco", "Marcos", "Margarita", "Mariam",
    "Mariana", "Marianne", "Marie", "Marisa", "Marisol", "Marissa", "Marjorie", "Marlene", "Marlon",
    "Marquis", "Marshall", "Marta", "Marty", "Mathew", "Mathias", "Matilda", "Maverick", "Maxim",
    "Maximilian", "Maya", "Mayra", "Mckenzie", "Meadow", "Meagan", "Melina", "Melody", "Mika", "Milo",
    "Mira", "Monroe", "Monserrat", "Moriah", "Mya", "Myra",
    # N
    "Nadine", "Naya", "Neela", "Nehemiah", "Nevaeh", "Nico", "Nicolette", "Nigel", "Nikki", "Noe",
    "Nova",
    # O
    "Obadiah", "Octavia", "Odessa", "Odin", "Omari", "Orson", "Osiris",
    # P
    "Paola", "Payton", "Pedro", "Petra", "Peyton", "Phoenix", "Pia", "Presley", "Preston",
    # Q
    "Quiana", "Quincy", "Quinlan", "Quinten", "Quinton",
    # R
    "Raina", "Ramon", "Rashad", "Raven", "Rayden", "Raylan", "Reagan", "Reanna", "Reece", "Regan",
    "Remi", "Remy", "Rhema", "Rhett", "Ricardo", "Rocco", "Rogelio", "Ronan", "Ronnie", "Rosalie",
    "Rosalind", "Rosalyn", "Rosie", "Ryder",
    # S
    "Sage", "Salvador", "Samara", "Serenity", "Shari", "Shea", "Shelley", "Shiloh", "Siena", "Sky",
    "Storm", "Susanna",
    # T
    "Talia", "Tanner", "Tatiana", "Tate", "Tatum", "Thea", "Tiana", "Tobias", "Tucker", "Ty",
    # U
    "Uri", "Uriah",
    # V
    "Vance", "Vaughn", "Veda", "Velma", "Verna", "Violeta", "Virginia", "Vivienne",
    # W
    "Waylon", "Wes", "Weston", "Winston", "Winona", "Wren",
    # X
    "Xandra", "Xavion", "Xiomara", "Xochitl",
    # Y
    "Yahir", "Yana", "Yara", "Yehuda", "Youssef", "Yuna", "Yuri",
    # Z
    "Zadie", "Zain", "Zaire", "Zander", "Zaria", "Zion",
]

# 统一名字池：去重后按字母升序排列，保证规模为 500 个
NAMES: List[str] = sorted(
    dict.fromkeys(MALE_NAMES + FEMALE_NAMES + ADDITIONAL_NAMES)
)
if len(NAMES) < 500:
    raise ValueError(
        f"Name pool too small ({len(NAMES)}). Please add more names to reach 500."
    )
if len(NAMES) > 500:
    NAMES = NAMES[:500]


class NameGenerator:
    """分配唯一英文名字（不区分性别，随机分配）。"""

    def __init__(self, names: Iterable[str] | None = None) -> None:
        self._pool = self._prepare_pool(names or NAMES)
        self._assigned: Dict[str, str] = {}

    @staticmethod
    def _prepare_pool(source: Iterable[str]) -> Deque[str]:
        unique_names = list(dict.fromkeys(source))
        random.shuffle(unique_names)
        return deque(unique_names)

    def assign(self, gender_map: Dict[str, str]) -> Dict[str, str]:
        """为每个条目分配唯一名字，忽略性别信息。"""
        results: Dict[str, str] = {}
        for filename in gender_map.keys():
            results[filename] = self._next_name()
        return results

    def _next_name(self) -> str:
        if self._pool:
            name = self._pool.popleft()
            self._assigned[name] = "assigned"
            return name
        raise RuntimeError("名字池已耗尽，无法继续分配。")

    @property
    def assigned(self) -> Dict[str, str]:
        """返回已经分配过的名字，便于调试或日志记录。"""
        return self._assigned.copy()