from __future__ import annotations

import random
from collections import deque
from typing import Deque, Dict, Iterable, List

MALE_NAMES: List[str] = [
    "Aaron",
    "Adam",
    "Adrian",
    "Alan",
    "Albert",
    "Alex",
    "Alfred",
    "Andrew",
    "Anthony",
    "Arnold",
    "Arthur",
    "Austin",
    "Benjamin",
    "Blake",
    "Brandon",
    "Brian",
    "Bruce",
    "Bryan",
    "Caleb",
    "Cameron",
    "Carl",
    "Carlos",
    "Carter",
    "Charles",
    "Chris",
    "Christian",
    "Christopher",
    "Clayton",
    "Cody",
    "Colin",
    "Connor",
    "Craig",
    "Damian",
    "Daniel",
    "Darren",
    "David",
    "Dean",
    "Dennis",
    "Derek",
    "Dominic",
    "Donald",
    "Douglas",
    "Dylan",
    "Edward",
    "Elijah",
    "Eric",
    "Ethan",
    "Evan",
    "Felix",
    "Francis",
    "Frank",
    "Gabriel",
    "Gareth",
    "Gavin",
    "George",
    "Gerald",
    "Grant",
    "Gregory",
    "Harold",
    "Harry",
    "Henry",
    "Howard",
    "Hugh",
    "Hunter",
    "Ian",
    "Isaac",
    "Jack",
    "Jacob",
    "Jake",
    "James",
    "Jason",
    "Jeffrey",
    "Jeremy",
    "Jesse",
    "Jim",
    "Joel",
    "John",
    "Jonah",
    "Jonathan",
    "Jordan",
    "Joseph",
    "Joshua",
    "Justin",
    "Keith",
    "Kenneth",
    "Kevin",
    "Kyle",
    "Lance",
    "Larry",
    "Lawrence",
    "Leo",
    "Leonard",
    "Liam",
    "Logan",
    "Louis",
    "Lucas",
    "Marcus",
    "Mark",
    "Martin",
    "Mason",
    "Matthew",
    "Michael",
    "Mitchell",
    "Nathan",
    "Nicholas",
    "Noah",
    "Oliver",
    "Oscar",
    "Patrick",
    "Paul",
    "Peter",
    "Philip",
    "Raymond",
    "Richard",
    "Robert",
    "Roger",
    "Ryan",
    "Samuel",
    "Scott",
    "Sean",
    "Simon",
    "Spencer",
    "Stephen",
    "Steven",
    "Thomas",
    "Timothy",
    "Victor",
    "Vincent",
    "Walter",
    "Wayne",
    "Wesley",
    "William",
    "Zachary",
]

FEMALE_NAMES: List[str] = [
    "Abigail",
    "Ada",
    "Addison",
    "Alexandra",
    "Alicia",
    "Allison",
    "Alyssa",
    "Amanda",
    "Amber",
    "Amelia",
    "Amy",
    "Andrea",
    "Angela",
    "Anna",
    "Anne",
    "Annie",
    "April",
    "Ariana",
    "Ashley",
    "Audrey",
    "Autumn",
    "Ava",
    "Barbara",
    "Bella",
    "Bethany",
    "Beverly",
    "Bianca",
    "Brenda",
    "Brianna",
    "Brooke",
    "Candice",
    "Carla",
    "Carmen",
    "Caroline",
    "Cassandra",
    "Catherine",
    "Charlotte",
    "Chloe",
    "Christina",
    "Christine",
    "Claire",
    "Clara",
    "Courtney",
    "Daisy",
    "Dana",
    "Danielle",
    "Deborah",
    "Denise",
    "Destiny",
    "Diana",
    "Donna",
    "Dorothy",
    "Eden",
    "Edith",
    "Eleanor",
    "Elena",
    "Elisa",
    "Elizabeth",
    "Ella",
    "Ellen",
    "Emily",
    "Emma",
    "Erica",
    "Erin",
    "Esme",
    "Esther",
    "Eva",
    "Evelyn",
    "Faith",
    "Felicia",
    "Fiona",
    "Flora",
    "Frances",
    "Gabriella",
    "Gail",
    "Gemma",
    "Georgia",
    "Grace",
    "Haley",
    "Hannah",
    "Heather",
    "Heidi",
    "Helen",
    "Holly",
    "Isabella",
    "Jackie",
    "Jade",
    "Jamie",
    "Jane",
    "Jasmine",
    "Jenna",
    "Jennifer",
    "Jessica",
    "Jill",
    "Joanna",
    "Jocelyn",
    "Jordan",
    "Josephine",
    "Joy",
    "Judith",
    "Julia",
    "Julie",
    "June",
    "Kaitlyn",
    "Karen",
    "Katherine",
    "Kathleen",
    "Kayla",
    "Kelly",
    "Kelsey",
    "Kimberly",
    "Kristin",
    "Kylie",
    "Laura",
    "Lauren",
    "Leah",
    "Lillian",
    "Lily",
    "Linda",
    "Lindsay",
    "Lisa",
    "Lola",
    "Lucia",
    "Lucy",
    "Lydia",
    "Madison",
    "Maggie",
    "Margaret",
    "Maria",
    "Mariah",
    "Martha",
    "Megan",
    "Melanie",
    "Melissa",
    "Mia",
    "Michelle",
    "Molly",
    "Monica",
    "Nadia",
    "Naomi",
    "Natalie",
    "Nicole",
    "Nina",
    "Olivia",
    "Paige",
    "Patricia",
    "Paula",
    "Pearl",
    "Penelope",
    "Phoebe",
    "Rachel",
    "Rebecca",
    "Riley",
    "Rose",
    "Sabrina",
    "Samantha",
    "Sandra",
    "Sara",
    "Sarah",
    "Savannah",
    "Scarlett",
    "Sophia",
    "Sophie",
    "Stacy",
    "Stephanie",
    "Susan",
    "Sydney",
    "Taylor",
    "Teresa",
    "Tiffany",
    "Vanessa",
    "Veronica",
    "Victoria",
    "Violet",
    "Vivian",
    "Wendy",
    "Whitney",
    "Zoe",
]


class NameGenerator:
    """根据性别结果分配唯一英文名字。"""

    def __init__(
        self,
        male_names: Iterable[str] | None = None,
        female_names: Iterable[str] | None = None,
    ) -> None:
        self._male_pool = self._prepare_pool(male_names or MALE_NAMES)
        self._female_pool = self._prepare_pool(female_names or FEMALE_NAMES)
        neutral = list(dict.fromkeys(MALE_NAMES + FEMALE_NAMES))
        random.shuffle(neutral)
        self._neutral_pool: Deque[str] = deque(neutral)
        self._assigned: Dict[str, str] = {}

    @staticmethod
    def _prepare_pool(source: Iterable[str]) -> Deque[str]:
        unique_names = list(dict.fromkeys(source))
        random.shuffle(unique_names)
        return deque(unique_names)

    def assign(self, gender_map: Dict[str, str]) -> Dict[str, str]:
        """为每张图片分配唯一名字。"""
        results: Dict[str, str] = {}
        for filename, gender in gender_map.items():
            gender_key = gender if gender in {"male", "female"} else None
            results[filename] = self._next_name(gender_key)
        return results

    def _next_name(self, gender: str | None) -> str:
        pools: List[Deque[str]] = []
        if gender == "male":
            pools.append(self._male_pool)
        elif gender == "female":
            pools.append(self._female_pool)
        pools.append(self._neutral_pool)

        for pool in pools:
            if pool:
                name = pool.popleft()
                self._assigned[name] = gender or "neutral"
                return name

        raise RuntimeError("名字池已耗尽，无法继续分配。")

    @property
    def assigned(self) -> Dict[str, str]:
        """返回已经分配过的名字，便于调试或日志记录。"""
        return self._assigned.copy()
